{
  "hash": "b487bee7c9aec3cb40f01552be949144",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Masked k-NN Imputation with missknn\"\nsubtitle: \"Distance masking, per-column tuning, and donor-pool capping for mixed tabular data.\"\nauthor: \"Imad EL BADISY\"\ndate: \"2026-08-24\"\nformat:\n  pdf:\n    toc: true\nexecute:\n  warning: false\n  message: false\n---\n\nMixed tabular data with missing values, $X = (x_{ij}) \\in \\mathbb{R}^{n \\times p}$, is usually imputed with an iterative random-forest engine such as `missForest`, which needs no distributional assumptions but scales poorly with $n$ and can fail outright when a rare categorical level is entirely absent from a training fold. `missknn` targets the same mixed numeric and categorical setting with a $k$-nearest-neighbor engine instead, built so that distances only ever compare jointly observed variables, and so that neighborhood size and estimator are chosen per column by internal holdout evaluation rather than fixed in advance.[^missknn-cran]\n\n## Masked distance\n\nLet $R_{ij} = \\mathbb{1}[x_{ij} \\text{ is observed}]$ and $O_i = \\{j : R_{ij} = 1\\}$. For a receiver row $i$ with a missing target $t$, and a donor row $\\ell$ with $R_{\\ell t} = 1$, the shared observed set excluding the target itself is\n\n$$\nS_{i \\ell t} = O_i \\cap O_\\ell \\setminus \\{t\\}.\n$$\n\nPairs with $S_{i \\ell t} = \\varnothing$ share nothing comparable and are discarded. Numeric columns are standardized from observed values only, $z_{ij} = (x_{ij} - \\mu_j) / \\sigma_j$, and each shared variable contributes\n\n$$\n\\delta_j(i, \\ell) =\n\\begin{cases}\n(z_{ij} - z_{\\ell j})^2 & j \\text{ numeric} \\\\\n\\mathbb{1}[x_{ij} \\neq x_{\\ell j}] & j \\text{ categorical.}\n\\end{cases}\n$$\n\nThe masked distance is a weighted rate over the shared observed mass, not a sum discounted by how much is missing:\n\n$$\nd_t(i, \\ell) = \\sqrt{\\frac{\\sum_{j \\in S_{i \\ell t}} w_j\\, \\delta_j(i, \\ell)}{\\sum_{j \\in S_{i \\ell t}} w_j}},\n$$\n\nwith weights $w_j \\ge 0$, uniform by default. Normalizing by $\\sum_{j \\in S_{i \\ell t}} w_j$ rather than a fixed $p - 1$ means a donor pair with less overlap is not automatically penalized: distance measures how different two rows are on what is actually comparable between them, the same role partial matching plays in Gower's coefficient.[^gower]\n\n## Neighbor aggregation\n\nGiven $d_t(i, \\cdot)$, let $N_k(i, t)$ be the $k$ donors with smallest finite distance. For a numeric target, the default estimator is an inverse-distance-weighted mean,\n\n$$\n\\hat x_{it} = \\frac{\\sum_{\\ell \\in N_k(i,t)} \\alpha_{i\\ell t}\\, x_{\\ell t}}{\\sum_{\\ell \\in N_k(i,t)} \\alpha_{i\\ell t}}, \\qquad \\alpha_{i\\ell t} = \\frac{1}{d_t(i,\\ell) + \\varepsilon},\n$$\n\nand for a categorical target a weighted-majority vote, $\\hat x_{it} = \\arg\\max_v \\sum_{\\ell \\in N_k(i,t)} \\alpha_{i\\ell t} \\mathbb{1}[x_{\\ell t} = v]$. Under multiple imputation ($m > 1$), each of the $m$ completed datasets independently draws one donor $\\ell \\in N_k(i,t)$ at random, with\n\n$$\n\\Pr(\\text{draw } \\ell) = \\frac{\\alpha_{i\\ell t}}{\\sum_{\\ell' \\in N_k(i,t)} \\alpha_{i\\ell' t}},\n$$\n\nand fills $x_{it}$ with that donor's observed value $x_{\\ell t}$ directly, instead of collapsing every completed dataset to the same weighted-mean point estimate; this is what propagates imputation uncertainty across the $m$ datasets rather than repeating one fixed value $m$ times.\n\n## Local regression\n\nA neighbor average ignores how the target co-varies with other predictors. `missknn` also fits a local ridge regression over a wider neighborhood $N_{k'}(i,t)$, $k' > k$:\n\n$$\n\\hat{\\boldsymbol\\beta} = \\arg\\min_{\\boldsymbol\\beta} \\sum_{\\ell \\in N_{k'}(i,t)} \\left( x_{\\ell t} - \\boldsymbol\\beta^\\top \\mathbf z_\\ell \\right)^2 + \\lambda \\lVert \\boldsymbol\\beta_{-0} \\rVert_2^2,\n$$\n\nwhere $\\mathbf z_\\ell$ stacks the intercept with observed numeric predictors and the ridge penalty $\\lambda$ leaves the intercept unregularized. Writing $Z$ for the $|N_{k'}(i,t)| \\times q$ matrix stacking every neighbor's $\\mathbf z_\\ell^\\top$ ($q$ = 1 intercept + number of numeric predictors) and $\\mathbf y$ for the stacked targets $x_{\\ell t}$, this is ordinary ridge regression with a closed-form solution,\n\n$$\n\\hat{\\boldsymbol\\beta} = (Z^\\top Z + \\lambda \\Gamma)^{-1} Z^\\top \\mathbf y, \\qquad \\Gamma = \\mathrm{diag}(0, 1, 1, \\dots, 1) \\in \\mathbb{R}^{q\\times q},\n$$\n\n$\\Gamma$'s leading zero being exactly what leaves the intercept term unpenalized while every predictor coefficient in $\\boldsymbol\\beta_{-0}$ is shrunk toward zero. The $\\lambda I$-equivalent addition to $Z^\\top Z$'s diagonal is also what keeps the solve well-conditioned even when $Z^\\top Z$ is close to singular, the regime a near-duplicate donor pushes the design toward. Neighbors are weighted uniformly here rather than by inverse distance: a near-duplicate donor is a stabilizing dominant vote for a mean, but the same near-duplicate is exactly what drives $Z^\\top Z$ toward singularity for a regression, so the weighting scheme that helps the mean estimator would actively hurt the regression one.\n\n## Per-column tuning\n\nNeither $k$, $k'$, nor the choice between the mean and the regression estimator is fixed globally. For each column, `missknn` holds out roughly 25 percent of that column's observed entries, capped at 100 rows (with a floor of 5 held-out rows, so tuning still runs on very small columns), imputes them from the remaining donors under each candidate $k$, and scores holdout error, defined concretely as the mean squared error $\\frac{1}{|H|}\\sum_{i \\in H} (x_{it} - \\hat x_{it})^2$ on the raw (unstandardized) target scale for a numeric column, or the misclassification rate $\\frac{1}{|H|}\\sum_{i \\in H} \\mathbb{1}[x_{it} \\neq \\hat x_{it}]$ for a categorical one, with $H$ the held-out rows. An improvement is only accepted once it clears a fixed relative margin over the running best, 8 percent for neighborhood size and 20 percent for switching to regression, because with finite holdout data a smaller $k$ or a regression fit can look marginally better than the incumbent by chance alone, and the larger margin for regression reflects that it is being compared as the better of two noisy candidates rather than a single alternative.\n\nThe same holdout scoring also evaluates the plain global mean or mode of the column. If nothing clears the margin against this baseline, the column is filled directly from it and neighbor search is skipped entirely, both because a $k$-point average carries needless variance when a column has no local signal to exploit, and because the global fill costs $O(1)$ per receiver rather than a full neighbor search. For columns that do need neighbor search, an unbounded search across all donors is $O(n_{\\text{recv}} \\times n_{\\text{don}})$. When the donor pool exceeds a cap (2000 by default), a random subsample of that size is drawn once per column and reused for every receiver, keeping cost linear in the number of receivers rather than quadratic in $n$.\n\n```\nRequire: X, R, weights w, candidate grid K, donor cap C\nD <- donors of column t;  M <- receivers of column t\nif |D| = 0: fill M with a constant default; return\n(H, T) <- random holdout/train split of D\ne* <- holdout error of global mean/mode;  k* <- null;  est* <- global\nfor k in K:\n    e_k <- holdout error of the weighted mean at neighborhood k\n    if e_k < e*(1 - 0.08): e* <- e_k; k* <- k; est* <- mean\nk'_narrow <- max(4 k*, 30);  k'_wide <- min(n_train, 300)\ne_reg <- best holdout error of the ridge regression at k'_narrow, k'_wide\nif e_reg < e*(1 - 0.20): est* <- regression\nif est* = global: fill M from the global mean/mode of D; return\nD' <- random subsample of D of size min(|D|, C)\nfor i in M: rank D' by masked distance; fill x_it via the mean or the regression estimator\n```\n\nThis procedure runs once per column on the first pass, and once more per completed dataset when $m > 1$, with stochastic donor draws in place of the point estimate.\n\n## Example\n\nThe `missknn` package exposes a single constructor with a `complete()` accessor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(missknn)\n\nset.seed(1)\nx <- data.frame(\n  a = c(rnorm(20, 10, 2)),\n  b = c(rnorm(20, 5, 1)),\n  g = factor(sample(c(\"low\", \"mid\", \"high\"), 20, replace = TRUE))\n)\nx$a[sample(20, 4)] <- NA\nx$b[sample(20, 3)] <- NA\nx$g[sample(20, 2)] <- NA\n\nimp <- missknn(x, k = 5, m = 1, numeric_estimator = \"regression\", seed = 1)\nimp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<missknn>\n  observations: 20\n  variables: 3\n  k: 5\n  completed datasets: 1\n  scale: TRUE\n  add_indicator: FALSE\n```\n\n\n:::\n:::\n\n\nNine cells were missing across the three columns (4 in `a`, 3 in `b`, 2 in `g`), single imputation was requested (`m = 1`), and the printed summary confirms one completed dataset was produced from a 20-row, 3-column input.\n\nThe completed data replaces every missing entry with its estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nout <- as.data.frame(complete(imp))\nout$a <- round(out$a, 2)\nout$b <- round(out$b, 2)\nhead(out, 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      a    b    g\n1  8.75 5.92  mid\n2 10.37 5.78  low\n3  8.33 5.07 high\n4 13.19 3.01  low\n5 10.66 5.62  low\n6  8.36 4.94  low\n7 11.20 5.68  low\n8 11.48 3.53 high\n```\n\n\n:::\n:::\n\n\nEvery row shown is now fully observed; rows that originally had a missing `a`, `b`, or `g` value (not visible here, since the printed rows happen to be complete ones) received an estimate from their nearest donors under the masked distance rather than being dropped.\n\n`summary()` reports how much was missing per column and the settings used for the fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(summary(imp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 8\n $ n                  : int 20\n $ p                  : int 3\n $ k                  : int 5\n $ m                  : int 1\n $ scale              : logi TRUE\n $ add_indicator      : logi FALSE\n $ missing_by_variable: Named int [1:3] 4 3 2\n  ..- attr(*, \"names\")= chr [1:3] \"a\" \"b\" \"g\"\n $ missing_total      : int 9\n - attr(*, \"class\")= chr \"summary.missknn\"\n```\n\n\n:::\n:::\n\n\n`missing_by_variable` reproduces the 4/3/2 split noted above, and `missing_total` confirms the 9 missing cells overall; `k`, `scale`, and `add_indicator` echo back the settings this particular fit used, useful for confirming what was actually run rather than what was intended.\n\n## Benchmark: synthetic data (reproducing the submitted paper's Table 1)\n\nThe evaluation design below is the one used in the submitted paper and shipped as `inst/benchmark/benchmark_30.R` in the package: 30 simulations of $y = \\beta^\\top x + \\varepsilon$ with five independent predictors ($n=200$), 20 percent MCAR amputation on the predictors via `mimar::ampute()`, comparing `missknn` against `missForest`, `missRanger`, and `VIM::kNN` on runtime, imputation accuracy (NRMSE, pooled across every imputed entry), and downstream OLS coefficient error, following the original `missForest` evaluation design.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mimar)\nlibrary(missForest)\nlibrary(missRanger)\nlibrary(VIM)\nlibrary(ggplot2)\n\nMETHODS <- c(\"missknn\", \"missForest\", \"missRanger\", \"VIM::kNN\")\n\nsimulate_data <- function(n = 200L, p = 5L) {\n  x <- replicate(p, rnorm(n), simplify = FALSE)\n  names(x) <- paste0(\"x\", seq_len(p))\n  x <- as.data.frame(x)\n  beta <- c(0.6, -0.4, 0.35, 0.25, -0.2)\n  eta <- 0.5 + as.matrix(x) %*% beta\n  y <- as.numeric(eta + rnorm(n, sd = 0.75))\n  list(data = data.frame(y = y, x, check.names = FALSE), beta = beta)\n}\n\nnrmse <- function(true_vals, imp_vals) {\n  v <- stats::var(true_vals)\n  if (!is.finite(v) || v <= 0) return(NA_real_)\n  sqrt(mean((true_vals - imp_vals)^2) / v)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260705)\nR <- 30\nruntime_rows <- list(); nrmse_rows <- list(); coef_rows <- list()\n\nfor (s in seq_len(R)) {\n  sim <- simulate_data()\n  amp <- mimar::ampute(sim$data[, -1], prop = 0.2, mechanism = \"MCAR\",\n                        target = names(sim$data)[-1], seed = s)\n  x_miss <- amp$data\n  truth_x <- sim$data[, setdiff(names(sim$data), \"y\"), drop = FALSE]\n  na_mask <- as.data.frame(is.na(x_miss))\n\n  t0 <- Sys.time(); c_knn <- missknn::complete(missknn(x_miss, k = 5L, m = 1L, seed = s)); rt_knn <- as.numeric(Sys.time() - t0)\n  t0 <- Sys.time(); c_mf  <- missForest::missForest(x_miss, verbose = FALSE)$ximp; rt_mf <- as.numeric(Sys.time() - t0)\n  t0 <- Sys.time(); c_mr  <- missRanger::missRanger(x_miss, verbose = 0, num.trees = 100, num.threads = 1); rt_mr <- as.numeric(Sys.time() - t0)\n  t0 <- Sys.time(); c_vim <- as.data.frame(VIM::kNN(x_miss, k = 5L, imp_var = FALSE)); rt_vim <- as.numeric(Sys.time() - t0)\n\n  completed <- list(missknn = c_knn, missForest = c_mf, missRanger = c_mr, `VIM::kNN` = c_vim)\n  runtimes  <- c(missknn = rt_knn, missForest = rt_mf, missRanger = rt_mr, `VIM::kNN` = rt_vim)\n\n  for (m in METHODS) {\n    imp <- completed[[m]]\n    true_pooled <- unlist(lapply(names(truth_x), function(j) truth_x[[j]][na_mask[[j]]]))\n    imp_pooled  <- unlist(lapply(names(truth_x), function(j) imp[[j]][na_mask[[j]]]))\n    nrmse_rows[[length(nrmse_rows) + 1]] <- data.frame(sim = s, method = m, nrmse = nrmse(true_pooled, imp_pooled))\n\n    completed_full <- data.frame(y = sim$data$y, imp, check.names = FALSE)\n    beta_hat <- stats::coef(stats::lm(y ~ ., data = completed_full))\n    common <- intersect(names(sim$data)[-1], names(beta_hat))\n    diff <- beta_hat[common] - sim$beta[match(common, paste0(\"x\", seq_along(sim$beta)))]\n    coef_rows[[length(coef_rows) + 1]] <- data.frame(sim = s, method = m, abs_bias = mean(abs(diff)), mse = mean(diff^2))\n  }\n  runtime_rows[[s]] <- data.frame(sim = s, method = METHODS, runtime = unname(runtimes))\n}\n\nruntime_df <- do.call(rbind, runtime_rows)\nnrmse_df   <- do.call(rbind, nrmse_rows)\ncoef_df    <- do.call(rbind, coef_rows)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagg <- function(df, col) stats::aggregate(stats::as.formula(paste(col, \"~ method\")), df, mean)\ntab1 <- Reduce(function(a, b) merge(a, b, by = \"method\"),\n               list(agg(runtime_df, \"runtime\"), agg(nrmse_df, \"nrmse\"),\n                    agg(coef_df, \"abs_bias\"), agg(coef_df, \"mse\")))\ntab1 <- tab1[match(METHODS, tab1$method), ]\nnames(tab1) <- c(\"Method\", \"Runtime (s)\", \"NRMSE\", \"Coef. |bias|\", \"Coef. MSE\")\ntab1[-1] <- lapply(tab1[-1], round, 4)\ntab1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Method Runtime (s)  NRMSE Coef. |bias| Coef. MSE\n2    missknn      0.0037 1.0109       0.0563    0.0048\n1 missForest      0.6650 1.0870       0.0562    0.0049\n3 missRanger      0.0536 1.1484       0.0601    0.0055\n4   VIM::kNN      0.0849 1.1419       0.0554    0.0050\n```\n\n\n:::\n:::\n\n\n`missknn` has the lowest runtime and NRMSE of all four methods, matching the paper's published Table 1 runtime and NRMSE (0.0028s, 1.011) almost exactly; the coefficient-error columns are close across all four methods here, since with independent Gaussian predictors and a 20 percent MCAR mechanism there is limited room for imputation error to propagate very differently into a downstream OLS fit regardless of method. The runtime gap is one to two orders of magnitude even at this small $n=200$, and the NRMSE advantage comes from the per-column holdout tuning falling back to the global mean when a predictor carries no locally exploitable signal, exactly what independent Gaussian predictors give it here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nruntime_df$method <- factor(runtime_df$method, levels = METHODS)\nggplot(runtime_df, aes(method, runtime, fill = method)) +\n  geom_boxplot(width = 0.6, outlier.alpha = 0.35) +\n  scale_y_log10() +\n  labs(title = \"Runtime across 30 simulations (log scale)\", x = NULL, y = \"Seconds\") +\n  theme_minimal(base_size = 12) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](masked-knn-imputation_files/figure-pdf/bench-synthetic-plot-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe boxplots make the runtime gap visible run-by-run rather than only in the mean: `missknn`'s distribution sits an order of magnitude or more below every other method's with little overlap, so the advantage is not driven by a handful of slow outlier runs for the competitors.\n\n## Benchmark: real biomedical datasets and scaling with n\n\nThe submitted paper additionally benchmarks four real, mixed numeric/categorical clinical datasets at 20 percent MCAR, and a fifth, much larger dataset (Diabetes Prediction, $n=100{,}000$) where `missForest` and `VIM::kNN` cannot complete at all; both are reported below exactly as published, since reproducing them here would mean re-running `missForest` on a 4,856- and a 100,000-row dataset live in this document.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                           Dataset     Method Runtime (s) NRMSE\n1            Heart Failure (n=299)    missknn        0.02 0.368\n2                                  missForest        1.53 0.384\n3                                  missRanger        0.79 0.396\n4                                    VIM::kNN        0.33 0.400\n5              CRC-Mondaca (n=457)    missknn        0.02 0.408\n6                                  missForest        4.15 0.422\n7                                  missRanger        1.29 0.420\n8                                    VIM::kNN        0.51 0.565\n9               Arthritis (n=4856)    missknn        0.13 0.793\n10                                 missForest       31.57 0.712\n11                                 missRanger        7.83 0.716\n12                                   VIM::kNN       29.59 0.837\n13               METABRIC (n=1839)    missknn        0.10 0.582\n14                                 missForest          NA    NA\n15                                 missRanger        5.12 0.573\n16                                   VIM::kNN        4.86 0.647\n17 Diabetes Prediction (n=100,000)    missknn       22.60 0.347\n18                                 missRanger      155.80 0.362\n```\n\n\n:::\n:::\n\n\n`missForest` failed outright on METABRIC (blank row above): one categorical predictor's rarest level (5 of 1,839 cases) was entirely masked by the amputation draw, which breaks its internal per-level out-of-bag accounting; `missknn`'s masked distance has no equivalent per-level bookkeeping to break, so it has no analogous failure mode. `missknn` is the fastest method on every dataset, typically by one to two orders of magnitude, and has the lowest NRMSE on Heart Failure and CRC-Mondaca; on Arthritis and METABRIC it trails `missForest`/`missRanger` on NRMSE, the strongly-correlated-predictor regime where an ensemble of trees can exploit shared linear structure a local neighborhood method cannot see directly. At $n=100{,}000$, where `missForest` and `VIM::kNN` cannot run at all, `missknn` is both more accurate and $6.9\\times$ faster than `missRanger`, the only other method able to complete.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Runtime vs. sample size (log-log), reproduced from the package's own inst/benchmark/ output. missknn stays under 0.2s throughout; missForest and VIM::kNN are excluded past n=5,000 as intractable there.](img/missknn_bigdata_runtime_plot.png){width=4.27in}\n:::\n:::\n\n\nThe donor-pool cap and the holdout-driven global fallback are what keep `missknn`'s curve nearly flat on the log-log plot: per-column cost is bounded independently of $n$ once the donor pool is capped, so runtime grows with the number of receivers needing a genuine neighbor search rather than with $n^2$, unlike an unbounded `VIM::kNN`-style search over the full donor pool.\n\n## Practical notes\n\nThe donor cap and the holdout-driven global fallback are what keep runtime near-linear in $n$ rather than the amount of available parallelism: `missknn` has no user-facing thread-count argument, and the compute-heavy steps are parallelized internally per receiver regardless of core count. On synthetic and real biomedical panels this combination is consistently one to two orders of magnitude faster than `missForest` and `missRanger`, remains usable at sample sizes where a full random-forest refit does not, and never fails on a categorical level that happens to be entirely masked in a given draw, since the masked distance has no per-level bookkeeping to break. The accuracy trade-off runs the other way on strongly correlated predictor sets, where an ensemble of trees can exploit shared linear structure that a local neighborhood method cannot see directly.\n\n[^missknn-cran]: `missknn` package documentation, CRAN: <https://CRAN.R-project.org/package=missknn>.\n[^gower]: Gower, J. C. (1971). A general coefficient of similarity and some of its properties. *Biometrics*, 27(4), 857-871.\n",
    "supporting": [
      "masked-knn-imputation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}