{
  "hash": "fde067df2c8cd9b43f1b3676ab06d129",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Survival-Trajectory Phenotypes from Individualized Survival Curves with unsurv\"\nsubtitle: \"Validity projection, time-weighted integral distances, and medoid clustering for predicted survival curves.\"\nauthor: \"Imad EL BADISY\"\ndate: \"2026-07-27\"\nformat:\n  pdf:\n    toc: true\nexecute:\n  warning: false\n  message: false\n---\n\nUnsupervised phenotyping usually clusters molecular or clinical covariates and tests survival differences post hoc, which optimizes a covariate representation rather than the time-to-event prediction itself, and can miss structure expressed mainly through when risk accumulates. Many survival learners instead output individualized survival trajectories $\\hat S_i(t)$ rather than only a scalar risk score. `unsurv` clusters those trajectories directly: the input is a survival probability matrix, not the covariate matrix.[^unsurv-cran]\n\n## Input representation\n\nLet $n$ be the number of individuals and $t_1 < \\dots < t_Q$ a strictly increasing time grid. For individual $i$, the observed or predicted curve is $\\mathbf S_i = (S_i(t_1), \\dots, S_i(t_Q))$, stacked into a matrix $S \\in [0,1]^{n \\times Q}$. A mathematically valid survival curve lives in\n\n$$\n\\mathcal{S}_Q = \\{ \\mathbf u \\in [0,1]^Q : u_1 \\ge u_2 \\ge \\cdots \\ge u_Q \\},\n$$\n\nbounded and non-increasing. The goal is to partition the $n$ trajectories into $K$ clusters by similarity of temporal survival behavior, working directly with $S$ rather than with the covariates that produced it.\n\n## Validity projection\n\nPredicted curves from a flexible learner are not guaranteed to land in $\\mathcal{S}_Q$: small local irregularities can push values outside $[0,1]$ or briefly break monotonicity. `unsurv` applies a deterministic map $\\Pi : \\mathbb{R}^Q \\to \\mathcal{S}_Q$ before computing any distance.\n\nClamping bounds each value to $[0,1]$,\n\n$$\nS_i(t_q) \\leftarrow \\min\\{1, \\max\\{0, S_i(t_q)\\}\\}.\n$$\n\nMonotonicity enforcement then sweeps left to right, pulling each point down to no more than the already-corrected previous point,\n\n$$\nS_i(t_q) \\leftarrow \\min\\big(S_i(t_q), S_i(t_{q-1})\\big), \\qquad q = 2, \\dots, Q,\n$$\n\nwhich guarantees the non-increasing property by construction rather than by post hoc rejection. An optional median smoothing step with odd window width $w \\ge 3$ can follow,\n\n$$\nS_i(t_q) \\leftarrow \\operatorname{median}\\{ S_i(t_r) : r \\in [q-h, q+h] \\}, \\qquad h = (w-1)/2,\n$$\n\nuseful when curves come from a learner flexible enough to show small local wiggles that carry no real signal.\n\n## Time-weighted integral distances\n\nDistances are built to approximate normalized continuous-time integrals over the follow-up window, not raw pointwise sums. With $\\Delta_q = t_{q+1} - t_q$, trapezoidal quadrature weights are\n\n$$\nw_1 = \\tfrac12 \\Delta_1, \\qquad w_q = \\tfrac12(\\Delta_{q-1} + \\Delta_q) \\ (2 \\le q \\le Q-1), \\qquad w_Q = \\tfrac12 \\Delta_{Q-1},\n$$\n\nnormalized so that $\\sum_q w_q = 1$. For an $L_2$ distance, curves are mapped into a weighted Euclidean space by $x_{iq} = \\sqrt{w_q}\\, S_i(t_q)$, so that ordinary squared Euclidean distance recovers the discretized integral,\n\n$$\n\\lVert \\mathbf x_i - \\mathbf x_j \\rVert_2^2 = \\sum_{q=1}^Q w_q \\big(S_i(t_q) - S_j(t_q)\\big)^2 \\approx \\frac{1}{t_Q - t_1} \\int_{t_1}^{t_Q} \\big(S_i(t) - S_j(t)\\big)^2\\, dt.\n$$\n\nTaking the square root of the quadrature weight before differencing is what lets a plain Euclidean norm on the transformed matrix stand in for a time integral of a squared term. For an $L_1$ distance the weight is applied without the square root, since the absolute-value term is linear rather than quadratic, $x_{iq} = w_q\\, S_i(t_q)$, giving\n\n$$\n\\lVert \\mathbf x_i - \\mathbf x_j \\rVert_1 = \\sum_{q=1}^Q w_q \\big| S_i(t_q) - S_j(t_q) \\big| \\approx \\frac{1}{t_Q - t_1} \\int_{t_1}^{t_Q} \\big| S_i(t) - S_j(t) \\big|\\, dt.\n$$\n\nOptional per-column standardization can follow the weighting step when early and late follow-up regions sit on very different scales, as can happen with long follow-up.\n\n## Medoid clustering\n\nGiven the embedded feature matrix, `unsurv` computes a pairwise dissimilarity matrix, Euclidean for $L_2$ and Manhattan for $L_1$, and applies partitioning around medoids.[^pam] For medoid indices $M = \\{m_1, \\dots, m_K\\}$, the fitted partition minimizes\n\n$$\n\\sum_{i=1}^n \\min_{m \\in M} d(\\mathbf x_i, \\mathbf x_m).\n$$\n\nEach cluster prototype under this scheme is an observed curve, not an averaged one, so the reported prototype is always a real, valid patient trajectory, and the method accepts any dissimilarity rather than requiring one compatible with a centroid update.\n\nExact minimization of the PAM objective over all $\\binom{n}{K}$ possible medoid sets is NP-hard, so `cluster::pam()` solves it by the classical two-phase heuristic. **BUILD** constructs an initial medoid set greedily: the first medoid is the observation minimizing total dissimilarity to all others, and each subsequent medoid is the not-yet-selected point whose addition to the current set produces the largest reduction in the objective, until $K$ medoids are chosen. **SWAP** then iterates: for every (medoid, non-medoid) pair, evaluate the change in the objective from swapping them, and carry out the single best swap found if it improves the objective, repeating until no swap improves it further, a local, not global, optimum in general (BUILD's greedy construction is what keeps the algorithm's typical performance close to the global optimum in practice, without guaranteeing it).\n\n`eps_jitter` (default $0.001$) adds independent $\\mathcal{N}(0, \\texttt{eps\\_jitter}^2)$ noise to every entry of the embedded feature matrix before computing dissimilarities, purely to break exact ties: two numerically identical or near-identical predicted curves would otherwise create zero or duplicate distances, which can make BUILD's greedy tie-breaking and the silhouette computation below unstable or arbitrary; the jitter is small enough to leave genuine distances essentially unchanged while resolving degeneracies. Setting `eps_jitter = 0` (used in the fully reproducible examples in this note) disables it.\n\nIf $K$ is not specified, `unsurv` scans a candidate range $K \\in \\{2,\\dots,K_{\\max}\\}$, fits PAM at each, and selects the value maximizing mean silhouette width. For point $i$ assigned to cluster $C$, with $a(i)$ the mean dissimilarity to every other point in $C$ and $b(i)$ the smallest such mean dissimilarity to any other cluster (the \"next best\" cluster for $i$),\n\n$$\n\\mathrm{sil}(i) = \\frac{b(i) - a(i)}{\\max(a(i), b(i))} \\in [-1, 1], \\qquad \\overline{\\mathrm{sil}} = \\frac{1}{n}\\sum_{i=1}^n \\mathrm{sil}(i),\n$$\n\nso $\\mathrm{sil}(i)$ near $1$ means $i$ sits much closer to its own cluster than to the nearest alternative (well clustered), near $0$ means it is roughly equidistant from both (on a boundary), and negative means it is on average closer to another cluster than to its own (plausibly mis-clustered); $K$ is chosen to maximize the average of this quantity over all $n$ curves, a pragmatic exploratory default rather than an inferential test for the number of clusters.\n\n```\nRequire: S, time grid, preprocessing options, distance type, K or K_max\nApply clamping; optionally enforce monotonicity and smoothing\nCompute trapezoidal weights\nConstruct the weighted feature matrix under L1 or L2 mapping\nCompute pairwise dissimilarities\nif K unspecified: select K by silhouette scanning\nFit PAM; return labels and medoids\n```\n\n## Prediction for new patients\n\nFor a new curve $\\mathbf S_{\\text{new}}$ on the same time grid, `unsurv` applies the same validity map and feature embedding $\\Phi$ used at training time, then assigns the nearest medoid,\n\n$$\n\\hat c(\\mathbf S_{\\text{new}}) = \\arg\\min_k\\, d\\big( \\Phi(\\Pi(\\mathbf S_{\\text{new}})),\\ \\Phi(\\Pi(\\mathbf S_{m_k})) \\big).\n$$\n\nThis is well defined precisely because medoids are stored observed curves from training rather than a fitted functional form, so a new patient is assigned without refitting anything.\n\n## Stability\n\nBecause predicted curves inherit uncertainty from the upstream survival learner, `unsurv` reports stability under resampling, subsampling without replacement or bootstrap with replacement, with optional perturbations such as additive noise on curves followed by monotonicity enforcement, perturbation of the time weights, or feature-space jitter. Stability is summarized by the Adjusted Rand Index between resampled partitions on overlapping individuals, comparing the resampled clustering against the reference partition.\n\n## Example\n\nThis is the synthetic data-generating process used for the main figure of the `unsurv` application note: three latent risk regimes are simulated, `survdnn` learns individualized survival curves from covariates without ever seeing the latent regime label, and `unsurv` recovers the regimes from those predicted curves alone.[^unsurv-appendix]\n\nNinety patients per regime are drawn from cluster-specific Weibull event-time distributions with progressively larger shape and scale parameters across regimes, plus four covariates whose distributions also shift by regime and which perturb each patient's individual Weibull parameters, so the latent structure stays recoverable but is not a deterministic function of the observed covariates alone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\nlibrary(survdnn)\nlibrary(unsurv)\nlibrary(ggplot2)\nlibrary(patchwork)\n\nset.seed(123)\n\nsimulate_weibull_time <- function(shape, scale) {\n  scale * (-log(stats::runif(length(shape))))^(1 / shape)\n}\n\nn_per_cluster <- 90\ncluster_specs <- data.frame(\n  true_cluster = 1:3,\n  shape   = c(1.08, 1.35, 1.70),\n  scale   = c(6.0, 11.5, 19.5),\n  x1_mean = c(-2.4, 0.0, 2.4),\n  x2_mean = c(-1.6, 0.8, 2.8),\n  x3_prob = c(0.20, 0.50, 0.80),\n  x4_mean = c(2.0, 0.3, -1.2)\n)\n\nsim_list <- vector(\"list\", nrow(cluster_specs))\nfor (i in seq_len(nrow(cluster_specs))) {\n  spec <- cluster_specs[i, ]\n  x1 <- rnorm(n_per_cluster, spec$x1_mean, 0.55)\n  x2 <- rnorm(n_per_cluster, spec$x2_mean, 0.60)\n  x3 <- rbinom(n_per_cluster, 1, spec$x3_prob)\n  x4 <- rnorm(n_per_cluster, spec$x4_mean, 0.50)\n\n  shape_i <- pmax(0.8, rnorm(n_per_cluster, spec$shape + 0.03 * x3 - 0.02 * x4, 0.07))\n  scale_linpred <- 0.20 * x1 + 0.18 * x2 + 0.35 * x3 - 0.12 * x4\n  scale_i <- spec$scale * exp(0.10 * scale_linpred + rnorm(n_per_cluster, 0, 0.06))\n\n  event_time <- simulate_weibull_time(shape_i, scale_i)\n  censor_time <- runif(n_per_cluster, 10, 28)\n  sim_list[[i]] <- data.frame(\n    true_cluster = spec$true_cluster,\n    time   = pmin(event_time, censor_time),\n    status = as.integer(event_time <= censor_time),\n    x1 = x1, x2 = x2, x3 = x3, x4 = x4\n  )\n}\ndat <- do.call(rbind, sim_list)\n```\n:::\n\n\nA `survdnn` model is fit on a 70 percent training split using only the observed `(time, status)` outcome and the four covariates, never the latent regime label, and used to predict survival curves for the held-out 30 percent on a common 100-point grid up to the 90th percentile of training follow-up.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nidx_train <- sample.int(nrow(dat), floor(0.70 * nrow(dat)))\ntrain <- dat[idx_train, ]\ntest  <- dat[-idx_train, ]\n\nmod <- survdnn(\n  Surv(time, status) ~ x1 + x2 + x3 + x4,\n  data = train,\n  hidden = c(24, 12), activation = \"relu\",\n  dropout = 0, batch_norm = FALSE,\n  epochs = 160, lr = 5e-4,\n  loss = \"aft\", optimizer = \"adamw\",\n  optim_args = list(weight_decay = 1e-5),\n  .seed = 123, verbose = FALSE\n)\n\nt_max <- as.numeric(quantile(train$time, 0.90, na.rm = TRUE))\ntime_grid <- seq(0.1, t_max, length.out = 100)\nS_test <- as.matrix(predict(mod, newdata = test, type = \"survival\", times = time_grid))\n```\n:::\n\n\n`unsurv` then clusters the predicted test-set curves into $K=3$ groups, with monotonicity enforcement and light median smoothing against small local irregularities in the network output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- unsurv(\n  S = S_test, times = time_grid, K = 3, K_max = 3,\n  distance = \"L2\", enforce_monotone = TRUE, smooth_median_width = 3,\n  standardize_cols = FALSE, eps_jitter = 0, seed = 123\n)\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nunsurv (PAM) fit\n  K:3\n  distance:L2 silhouette_mean:0.732\n  n:81 Q:100\n```\n\n\n:::\n:::\n\n\nCluster labels from PAM are arbitrary integers, not ordered by risk, so they are relabeled by each medoid's row mean, a simple average-survival-level summary, before comparing against the known latent regime. Recovery is scored with the Adjusted Rand Index, computed directly from the contingency table rather than via `unsurv_compare()` (which compares partitions using observed outcomes, not against a known simulation label).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomb2 <- function(x) ifelse(x < 2, 0, x * (x - 1) / 2)\nadjusted_rand_index <- function(labels_true, labels_pred) {\n  tab <- table(labels_true, labels_pred)\n  n <- sum(tab)\n  sum_ij <- sum(comb2(tab)); sum_i <- sum(comb2(rowSums(tab))); sum_j <- sum(comb2(colSums(tab)))\n  expected <- sum_i * sum_j / comb2(n)\n  max_index <- 0.5 * (sum_i + sum_j)\n  if (max_index == expected) return(1)\n  (sum_ij - expected) / (max_index - expected)\n}\n\ncluster_order <- order(rowMeans(fit$medoids))\nrelabel <- setNames(seq_along(cluster_order), cluster_order)\npred_cluster <- unname(relabel[as.character(fit$clusters)])\n\ncontingency <- table(True = factor(test$true_cluster, levels = 1:3),\n                      Predicted = factor(pred_cluster, levels = 1:3))\ncontingency\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Predicted\nTrue  1  2  3\n   1 26  0  0\n   2  0 26  1\n   3  0  0 28\n```\n\n\n:::\n\n```{.r .cell-code}\naccuracy <- sum(diag(contingency)) / sum(contingency)\nari <- adjusted_rand_index(test$true_cluster, pred_cluster)\nc(accuracy = round(accuracy, 3), ari = round(ari, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\naccuracy      ari \n   0.988    0.962 \n```\n\n\n:::\n:::\n\n\nRecovery is close to exact: a single class-2 patient is placed in class 3, for a label-matched accuracy of 0.988 and an Adjusted Rand Index of 0.962, computed entirely from curves predicted on held-out patients, with the true regime label never used by either `survdnn` or `unsurv`.\n\n## Plots\n\nThe left panel is the raw model output passed to `unsurv()`, before clustering; the right panel is the same curves colored by the recovered phenotype with medoid prototypes overlaid, produced by `unsurv`'s own `plot()`/`autoplot()` method on the fitted object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve_df <- data.frame(\n  patient_id = rep(seq_len(nrow(S_test)), each = length(time_grid)),\n  time = rep(time_grid, times = nrow(S_test)),\n  surv = as.vector(t(S_test)),\n  cluster = factor(rep(pred_cluster, each = length(time_grid)), levels = 1:3)\n)\nS_med <- fit$medoids[cluster_order, , drop = FALSE]\nmed_df <- data.frame(\n  time = rep(time_grid, times = nrow(S_med)),\n  surv = as.vector(t(S_med)),\n  cluster = factor(rep(seq_len(nrow(S_med)), each = length(time_grid)), levels = 1:3)\n)\n\nfig_left <- ggplot(curve_df, aes(time, surv, group = patient_id)) +\n  geom_line(linewidth = 0.35, alpha = 0.35, color = \"grey35\") +\n  theme_minimal(base_size = 12) +\n  labs(x = \"Time\", y = \"Predicted survival probability\") +\n  theme(legend.position = \"none\")\n\nfig_right <- ggplot(curve_df, aes(time, surv, group = patient_id, color = cluster)) +\n  geom_line(linewidth = 0.40, alpha = 0.28) +\n  geom_line(data = med_df, aes(time, surv, group = cluster, color = cluster), linewidth = 1.3) +\n  theme_minimal(base_size = 12) +\n  scale_color_manual(values = c(\"1\" = \"#B22222\", \"2\" = \"#E69F00\", \"3\" = \"#1B9E77\")) +\n  labs(x = \"Time\", y = \"Predicted survival probability\", color = \"Cluster\") +\n  theme(legend.position = \"bottom\")\n\nfig_left + fig_right + plot_annotation(tag_levels = \"A\")\n```\n\n::: {.cell-output-display}\n![](survival-trajectory-phenotypes_files/figure-pdf/manuscript-figure-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nPanel A alone gives no indication of temporal-risk subgroups; panel B recovers three visually and numerically distinct trajectory groups directly from the predicted curves, without using the observed test-set outcomes at any point, illustrating the intended `unsurv` workflow: an upstream survival learner maps covariates to individualized trajectories, and `unsurv` converts those trajectories into interpretable temporal phenotypes.\n\n## METABRIC application\n\nThe synthetic example above confirms `unsurv` recovers known structure; this section applies the same pipeline to a real cohort, the METABRIC breast cancer dataset distributed with the `biostatlab` package, and adds two things the synthetic example could not: out-of-sample generalization to a genuinely held-out set, and a comparison against two baseline partitions built on the covariates rather than on predicted curves.[^unsurv-appendix]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(cluster)\n\nset.seed(20260615)\ndata(metabric, package = \"biostatlab\")\n\nraw <- metabric\nraw$os_time  <- raw$overall_survival_months\nraw$os_event <- raw$overall_survival\n\nexclude <- c(\"patient_id\", \"overall_survival_months\", \"overall_survival\", \"os_time\", \"os_event\", \"death_from_cancer\")\nnumeric_cols <- setdiff(names(raw)[vapply(raw, is.numeric, logical(1))], exclude)\ncomplete_rate <- vapply(raw[numeric_cols], function(x) mean(!is.na(x)), numeric(1))\nnumeric_cols <- numeric_cols[complete_rate >= 0.90]\nvars <- vapply(raw[numeric_cols], stats::var, numeric(1), na.rm = TRUE)\nvars <- vars[is.finite(vars) & vars > 0]\nselected <- names(sort(vars, decreasing = TRUE))[seq_len(min(120L, length(vars)))]\n\nmodel_df <- raw[, c(\"os_time\", \"os_event\", selected), drop = FALSE]\nmodel_df <- model_df[stats::complete.cases(model_df), , drop = FALSE]\nnames(model_df) <- make.names(names(model_df), unique = TRUE)\ncovariate_cols <- setdiff(names(model_df), c(\"os_time\", \"os_event\"))\n\nnrow(model_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1839\n```\n\n\n:::\n:::\n\n\nAfter keeping numeric predictors that are at least 90 percent observed and complete-case filtering, 1839 patients and 120 predictors remain, matching the cohort size reported in the application note. Patients are split three ways: a training set that only `survdnn` sees, a partition set used to fit `unsurv` and the two baselines, and a validation set held out from both, so cluster generalization can be checked directly rather than assumed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- nrow(model_df)\nidx_all <- sample.int(n)\nn_train <- floor(0.60 * n); n_partition <- floor(0.20 * n)\ntrain      <- model_df[idx_all[seq_len(n_train)], , drop = FALSE]\npartition  <- model_df[idx_all[n_train + seq_len(n_partition)], , drop = FALSE]\nvalidation <- model_df[idx_all[(n_train + n_partition + 1):n], , drop = FALSE]\n\nmod <- survdnn(\n  Surv(os_time, os_event) ~ .,\n  data = train,\n  hidden = c(64, 32), activation = \"relu\",\n  dropout = 0.10, batch_norm = TRUE,\n  epochs = 120, lr = 5e-4,\n  loss = \"aft\", optimizer = \"adamw\",\n  optim_args = list(weight_decay = 1e-5),\n  .seed = 20260615, verbose = FALSE\n)\n\nt_max <- as.numeric(quantile(train$os_time, 0.90, na.rm = TRUE))\ntime_grid <- seq(max(0.1, min(train$os_time[train$os_time > 0], na.rm = TRUE)), t_max, length.out = 100)\npred_partition  <- as.matrix(predict(mod, newdata = partition,  type = \"survival\", times = time_grid))\npred_validation <- as.matrix(predict(mod, newdata = validation, type = \"survival\", times = time_grid))\n\nc(train = nrow(train), partition = nrow(partition), validation = nrow(validation))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     train  partition validation \n      1103        367        369 \n```\n\n\n:::\n:::\n\n\nThe AFT loss is used deliberately, not arbitrarily: as the structural limitation below makes precise, a proportional-hazards learner would make curve-shape clustering here mathematically equivalent to clustering a scalar risk score, which would defeat the purpose of this application.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- unsurv(\n  S = pred_partition, times = time_grid, K = 3, K_max = 6,\n  distance = \"L2\", enforce_monotone = TRUE, smooth_median_width = 3,\n  standardize_cols = FALSE, eps_jitter = 0, seed = 20260615\n)\ntable(fit$clusters)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   3 \n121 102 144 \n```\n\n\n:::\n\n```{.r .cell-code}\nstab <- unsurv_stability(\n  S = pred_partition, times = time_grid, fit = fit, B = 30, frac = 0.70,\n  mode = \"subsample\", jitter_sd = 0.005, weight_perturb = 0.10,\n  eps_jitter = 0, return_distribution = TRUE\n)\nstab$mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8488424\n```\n\n\n:::\n:::\n\n\n`unsurv` with $K=3$ on the partition set gives clusters of size 121, 102, and 144, matching the application note's reported sizes, and resampling stability over 30 subsamples is good (mean ARI 0.849), meaning the partition is not an artifact of one particular sample draw.\n\nTwo baselines are fit on the same partition set: PAM on the scalar predicted risk at the median time-grid horizon, and PAM on the first five principal components of the training covariates. Validation-set patients are assigned out-of-sample to all three partitions (`unsurv` via `predict()`, nearest medoid; scalar risk via nearest cluster-mean risk; covariate PCA via nearest cluster-mean centroid in PCA-score space, with loadings fixed from the training set), and all three are relabeled by partition-set Kaplan-Meier median survival so label 1 is always the worst-survival cluster.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelabel_map_by_survival <- function(labels, time, status) {\n  old_levels <- sort(unique(as.integer(labels)))\n  meds <- vapply(old_levels, function(l) {\n    idx <- labels == l\n    sf <- survival::survfit(survival::Surv(time[idx], status[idx]) ~ 1)\n    m <- summary(sf)$table[\"median\"]\n    if (is.na(m)) Inf else as.numeric(m)\n  }, numeric(1))\n  setNames(seq_along(order(meds)), as.character(old_levels[order(meds)]))\n}\napply_map <- function(labels, map) unname(map[as.character(as.integer(labels))])\n\nhorizon_idx <- which.min(abs(time_grid - median(time_grid)))\nscalar_risk_partition  <- 1 - pred_partition[, horizon_idx]\nscalar_risk_validation <- 1 - pred_validation[, horizon_idx]\npam_scalar <- cluster::pam(as.matrix(scalar_risk_partition), k = 3)\nscalar_centroids <- vapply(sort(unique(pam_scalar$clustering)), function(k)\n  mean(scalar_risk_partition[pam_scalar$clustering == k]), numeric(1))\nscalar_labels_validation_raw <- vapply(scalar_risk_validation,\n  function(v) which.min(abs(v - scalar_centroids)), integer(1))\n\nx_train <- train[, covariate_cols, drop = FALSE]\nx_center <- vapply(x_train, mean, numeric(1)); x_scale <- vapply(x_train, sd, numeric(1)); x_scale[x_scale == 0] <- 1\npca <- prcomp(scale(x_train, center = x_center, scale = x_scale), rank. = 5)\nproject_pca <- function(df) {\n  x <- scale(df[, covariate_cols, drop = FALSE], center = x_center, scale = x_scale)\n  predict(pca, newdata = x)[, 1:5, drop = FALSE]\n}\npca_scores_partition <- project_pca(partition); pca_scores_validation <- project_pca(validation)\npam_pca <- cluster::pam(pca_scores_partition, k = 3)\npca_centroids <- t(vapply(sort(unique(pam_pca$clustering)), function(k)\n  colMeans(pca_scores_partition[pam_pca$clustering == k, , drop = FALSE]), numeric(5)))\nd2 <- outer(rowSums(pca_scores_validation^2), rowSums(pca_centroids^2), \"+\") - 2 * (pca_scores_validation %*% t(pca_centroids))\npca_labels_validation_raw <- max.col(-d2)\n\nmap_curve  <- relabel_map_by_survival(fit$clusters, partition$os_time, partition$os_event)\nmap_scalar <- relabel_map_by_survival(pam_scalar$clustering, partition$os_time, partition$os_event)\nmap_pca    <- relabel_map_by_survival(pam_pca$clustering, partition$os_time, partition$os_event)\n\npartition_labels <- list(\n  `unsurv curve` = apply_map(fit$clusters, map_curve),\n  `Scalar risk`  = apply_map(pam_scalar$clustering, map_scalar),\n  `Covariate PCA` = apply_map(pam_pca$clustering, map_pca)\n)\nvalidation_labels <- list(\n  `unsurv curve` = apply_map(predict(fit, pred_validation), map_curve),\n  `Scalar risk`  = apply_map(scalar_labels_validation_raw, map_scalar),\n  `Covariate PCA` = apply_map(pca_labels_validation_raw, map_pca)\n)\n\ncmp_partition  <- unsurv_compare(partition_labels,  partition$os_time,  partition$os_event,  reference = \"unsurv curve\")\ncmp_validation <- unsurv_compare(validation_labels, validation$os_time, validation$os_event, reference = \"unsurv curve\")\n\ncmp_partition$summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         method K min_size max_size    ari_ref\n1  unsurv curve 3      102      144 1.00000000\n2   Scalar risk 3       91      145 0.83344758\n3 Covariate PCA 3       94      158 0.01781246\n```\n\n\n:::\n\n```{.r .cell-code}\ncmp_validation$summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         method K min_size max_size    ari_ref\n1  unsurv curve 3       81      163 1.00000000\n2   Scalar risk 3       69      163 0.81007077\n3 Covariate PCA 3       85      173 0.08603131\n```\n\n\n:::\n:::\n\n\n`unsurv curve` is by definition perfectly self-similar (ARI = 1). The scalar-risk baseline is highly concordant with the curve-based partition on both sets (ARI $\\ge 0.80$), showing that at this single horizon the scalar summary already captures much of the ordering information present in the full curve for this particular model; the covariate-PCA baseline is nearly unrelated to it (ARI $\\le 0.09$ on both sets), since it clusters a structurally different representation, the original covariates rather than the model's survival predictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(\n  cbind(set = \"partition\",  cmp_partition$cluster_summary),\n  cbind(set = \"validation\", cmp_validation$cluster_summary)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          set cluster   n events median_survival        method\n1   partition       1 102     52        166.6667  unsurv curve\n2   partition       2 144     68        184.8000  unsurv curve\n3   partition       3 121     42        229.3333  unsurv curve\n4   partition       1  91     48        164.7333   Scalar risk\n5   partition       2 145     66        189.7333   Scalar risk\n6   partition       3 131     48        229.3333   Scalar risk\n7   partition       1  94     47        177.6333 Covariate PCA\n8   partition       2 115     50        193.1333 Covariate PCA\n9   partition       3 158     65        205.6000 Covariate PCA\n10 validation       1  81     40        159.7333  unsurv curve\n11 validation       2 163     63        186.5333  unsurv curve\n12 validation       3 125     37        243.1667  unsurv curve\n13 validation       1  69     39        152.3000   Scalar risk\n14 validation       2 163     60        186.6000   Scalar risk\n15 validation       3 137     41        240.2000   Scalar risk\n16 validation       1  85     34        167.4333 Covariate PCA\n17 validation       2 111     58        176.6000 Covariate PCA\n18 validation       3 173     48        240.2000 Covariate PCA\n```\n\n\n:::\n:::\n\n\nFor the curve-based partition, median survival increases monotonically with cluster label on both the partition set and the independent validation set, so the ordering \"cluster 3 has better survival than clusters 1 and 2\" generalizes to patients neither `survdnn` nor `unsurv` ever saw during fitting; the same monotone ordering holds for the scalar-risk baseline. The covariate-PCA baseline's partition-set separation between its two lowest clusters is visibly weaker (a smaller median-survival gap than the other two methods) and only closes on the validation set, consistent with it tracking a different, less risk-aligned signal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncluster_pal <- c(\"1\" = \"#B22222\", \"2\" = \"#E69F00\", \"3\" = \"#1B9E77\")\ncurve_labels_partition <- apply_map(fit$clusters, map_curve)\n\ncurve_df <- data.frame(\n  patient_id = rep(seq_len(nrow(pred_partition)), each = length(time_grid)),\n  time = rep(time_grid, times = nrow(pred_partition)),\n  survival = as.vector(t(pred_partition)),\n  cluster = factor(rep(curve_labels_partition, each = length(time_grid)))\n)\nmedoid_order <- apply_map(seq_len(nrow(fit$medoids)), map_curve)\nmedoids <- fit$medoids[order(medoid_order), , drop = FALSE]\nmedoid_df <- data.frame(\n  time = rep(time_grid, times = nrow(medoids)),\n  survival = as.vector(t(medoids)),\n  cluster = factor(rep(sort(medoid_order), each = length(time_grid)))\n)\n\np_curves <- ggplot(curve_df, aes(time, survival, group = patient_id, color = cluster)) +\n  geom_line(linewidth = 0.25, alpha = 0.20) +\n  geom_line(data = medoid_df, aes(time, survival, group = cluster, color = cluster), linewidth = 1.1) +\n  scale_color_manual(values = cluster_pal) +\n  labs(x = \"Months\", y = \"Predicted survival probability\", color = \"Cluster\") +\n  theme_minimal(base_size = 11) + theme(legend.position = \"bottom\")\n\np_km <- autoplot(unsurv_compare(list(`unsurv curve` = curve_labels_partition), partition$os_time, partition$os_event)) +\n  scale_color_manual(values = cluster_pal) +\n  labs(title = NULL) + theme(strip.text = element_blank())\n\np_curves + p_km + plot_annotation(tag_levels = \"A\")\n```\n\n::: {.cell-output-display}\n![](survival-trajectory-phenotypes_files/figure-pdf/metabric-figure-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nPanel A shows `survdnn`-predicted curves on the partition set colored by `unsurv` cluster with medoid prototypes overlaid; panel B is the corresponding Kaplan-Meier curve computed from the *observed* outcomes within each cluster, included to show that the curve-based partition, fit without ever using observed outcomes, recovers groups with genuinely distinct observed survival, not just distinct predicted curves.\n\n## A structural limitation worth carrying forward\n\nUnder a proportional-hazards model, every predicted curve is $S_i(t) = S_0(t)^{\\exp(\\eta_i)}$, a scalar power transform of one shared baseline. Any $L_1$ or $L_2$ curve-shape distance between two such curves reduces to a monotone function of the scalar linear predictor $\\eta_i$ alone, so clustering curve shapes under proportional hazards is mathematically equivalent to clustering a single number. `unsurv` is doing genuinely curve-native work only for learners that do not impose proportional hazards, such as random survival forests or a `survdnn` model fit with the AFT or Cox-Time loss, where curve shape carries information beyond one scalar summary.\n\n## Interpretation\n\nA practical reporting template is:\n\n- Cluster 1: slow decline in predicted survival, high expected event-free time.\n- Cluster 2: intermediate decline, moderate expected event-free time.\n- Cluster 3: rapid decline, low expected event-free time.\n\nAfter clustering, each phenotype should be described with survival probabilities at clinically meaningful horizons, restricted mean survival time summaries, and baseline covariate distributions, so the phenotype stays anchored to survival behavior while remaining interpretable to clinical collaborators. Partitions can be compared against alternative clusterings, such as one built on a scalar risk summary or on covariate principal components, with `unsurv_compare()`, which reports cluster sizes, Adjusted Rand Index agreement, and per-cluster Kaplan-Meier medians rather than a log-rank test, since testing a partition against the labels it was fit to separate is circular.\n\n[^unsurv-cran]: `unsurv` package documentation, CRAN: <https://CRAN.R-project.org/package=unsurv>.\n[^pam]: Kaufman, L., and Rousseeuw, P. J. (1990). *Finding Groups in Data: An Introduction to Cluster Analysis*. Wiley.\n[^unsurv-appendix]: EL BADISY, I. (2026). *unsurv: Clustering Individualized Survival Curves*. Application note, Bioinformatics Advances. Synthetic example and code reproduced from the manuscript's supplementary appendix.\n",
    "supporting": [
      "survival-trajectory-phenotypes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}